# Generated by Django 2.1.1 on 2018-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTIO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[('user', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', max_length=10, verbose_name='display rank'),
        ),
    ]
